---
- name: Clean configuration
  become: true
  file:
    dest: "/etc/rsyslog.d/{{ item }}"
    state: absent
  with_items:
    - 20-ufw.conf
    - 21-cloudinit.conf
    - 50-default.conf

- name: Configure rsyslog
  become: true
  template:
    dest: /etc/rsyslog.conf
    group: root
    mode: u=wr,go=
    owner: root
    src: templates/rsyslog.conf.j2
  notify:
    - reload rsyslog

- name: Create default rules
  become: true
  template:
    dest: /etc/rsyslog.d/default-rules.conf
    group: root
    mode: u=wr,go=
    owner: root
    src: templates/default-rules.conf.j2
  notify:
    - reload rsyslog
  when:
    - rsyslog_default_rules

- name: Remove default rules
  become: true
  file:
    dest: /etc/rsyslog.d/default-rules.conf
    state: absent
  when:
    - not rsyslog_default_rules
