---
- name: Clean configuration
  become: true
  file:
    dest: "{{ rsyslog_configuration_directory }}/{{ item }}"
    state: absent
  with_items:
    - 20-ufw.conf
    - 21-cloudinit.conf
    - 50-default.conf

- name: Configure rsyslog
  become: true
  template:
    dest: /etc/rsyslog.conf
    group: root
    mode: u=wr,go=
    owner: root
    src: templates/rsyslog.conf.j2
  notify:
    - reload rsyslog

- name: Create default config
  become: true
  template:
    dest: {{ rsyslog_default_configuration_file_name }}
    group: root
    mode: u=wr,go=
    owner: root
    src: templates/default-configuration.conf.j2
  notify:
    - reload rsyslog
  when:
    - rsyslog_default_configuration

- name: Remove default configuration
  become: true
  file:
    dest: {{ rsyslog_default_configuration_file_name }}
    state: absent
  when:
    - not rsyslog_default_configuration

- name: Create default rules
  become: true
  template:
    dest: {{ rsyslog_default_rules_file_name }}
    group: root
    mode: u=wr,go=
    owner: root
    src: templates/default-rules.conf.j2
  notify:
    - reload rsyslog
  when:
    - rsyslog_default_rules

- name: Remove default rules
  become: true
  file:
    dest: {{ rsyslog_default_rules_file_name }}
    state: absent
  when:
    - not rsyslog_default_rules
